// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  angular.module('moment.moment-filter', []).filter('moment', [
    'moment', function(moment) {
      return function(input, from, to) {
        if (to == null) {
          to = 'DD-MM-YYYY';
        }
        return moment(input, from).format(to);
      };
    }
  ]);

}).call(this);
