// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  angular.module('myApp', ['ui.router', 'partial-controllers', 'version', 'github-repos', 'moment', 'message']).controller('myAppCtrl', [
    '$scope', function($scope) {
      $scope.msgs = [];
      $scope.addMsg = function(style, text) {
        return $scope.msgs.push({
          style: style,
          text: text
        });
      };
      return $scope.removeMsg = function(id) {
        return $scope.msgs.splice(id, 1);
      };
    }
  ]).config([
    '$urlRouterProvider', '$stateProvider', function($urlRouterProvider, $stateProvider) {
      $urlRouterProvider.otherwise('/');
      return $stateProvider.state('home', {
        url: '/',
        templateUrl: 'partials/home.html',
        controller: 'HomeCtrl'
      }).state('github-repos', {
        url: '/github-repos',
        templateUrl: 'partials/github-repos.html',
        controller: 'GitHubReposCtrl'
      }).state('moment', {
        url: '/moment',
        templateUrl: 'partials/moment.html'
      });
    }
  ]);

}).call(this);
