// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  angular.module('app', ['ui.router', 'partial-controllers', 'version', 'github-repos', 'moment', 'message']).controller('MainCtrl', [
    '$scope', 'appName', function($scope, appName) {
      $scope.MainCtrl = {};
      $scope.MainCtrl.appName = appName;
      $scope.MainCtrl.msgs = [];
      $scope.MainCtrl.addMsg = function(style, text) {
        return $scope.MainCtrl.msgs.push({
          style: style,
          text: text
        });
      };
      return $scope.MainCtrl.removeMsg = function(index) {
        return $scope.MainCtrl.msgs.splice(index, 1);
      };
    }
  ]).constant('appName', 'meet.js Wrocław').config([
    '$urlRouterProvider', '$stateProvider', function($urlRouterProvider, $stateProvider) {
      $urlRouterProvider.otherwise('/');
      return $stateProvider.state('home', {
        url: '/',
        templateUrl: 'partials/home.html',
        controller: 'HomeCtrl'
      }).state('github-repos', {
        url: '/github-repos',
        templateUrl: 'partials/github-repos.html',
        controller: 'GitHubReposCtrl'
      }).state('moment', {
        url: '/moment',
        templateUrl: 'partials/moment.html'
      });
    }
  ]);

}).call(this);
