// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  describe('MainCtrl', function() {
    var scope;
    scope = null;
    beforeEach(module('app'));
    beforeEach(inject(function($rootScope, $controller) {
      scope = $rootScope.$new();
      $controller('MainCtrl', {
        '$scope': scope,
        appName: 'FakeAppName'
      });
      return scope.$digest();
    }));
    it('should have initial msgs and appName values', function() {
      expect(scope.MainCtrl.msgs).toEqual([]);
      return expect(scope.MainCtrl.appName).toEqual('FakeAppName');
    });
    it('should have addMsg method', function() {
      return expect(scope.MainCtrl.addMsg).toEqual(jasmine.any(Function));
    });
    return it('should add message with addMsg', function() {
      var msgsAfter, msgsBefore;
      msgsBefore = angular.copy(scope.MainCtrl.msgs);
      scope.MainCtrl.addMsg('success', 'Foo');
      msgsAfter = angular.copy(scope.MainCtrl.msgs);
      expect(msgsAfter.length).toBeGreaterThan(msgsBefore);
      return expect(msgsAfter[0]).toEqual({
        style: 'success',
        text: 'Foo'
      });
    });
  });

}).call(this);
