// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  describe('myAppCtrl', function() {
    var myAppCtrl, scope;
    myAppCtrl = scope = null;
    beforeEach(module('myApp'));
    beforeEach(inject(function($rootScope, $controller) {
      scope = $rootScope.$new();
      myAppCtrl = $controller('myAppCtrl', {
        '$scope': scope
      });
      return scope.$digest();
    }));
    it('should have initial msgs value', function() {
      return expect(scope.msgs).toEqual([]);
    });
    it('should have addMsg method', function() {
      return expect(scope.addMsg).toEqual(jasmine.any(Function));
    });
    return it('should add message with addMsg', function() {
      var msgsAfter, msgsBefore;
      msgsBefore = angular.copy(scope.msgs);
      scope.addMsg('success', 'Foo');
      msgsAfter = angular.copy(scope.msgs);
      expect(msgsAfter.length).toBeGreaterThan(msgsBefore);
      return expect(msgsAfter[0]).toEqual({
        style: 'success',
        text: 'Foo'
      });
    });
  });

}).call(this);
