// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  describe('version module', function() {
    beforeEach(module('version'));
    return describe('version service', function() {
      return it('should return current version', inject(function(version) {
        return expect(version).toEqual('1.0.0');
      }));
    });
  });

}).call(this);
